"use client";

import { useActionState, useState } from "react";
import { useRouter } from "next/navigation";
import { Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/cn";
import { createWorkflowAction } from "@/features/workflow-builder/actions/workflow-actions";

type Mode = "manual" | "ai";

/** Workflow creation entry point: empty (only a trigger node) or generated by Claude from a description. */
export function CreateWorkflowDialog({ formId }: { formId: string }) {
  const [open, setOpen] = useState(false);
  const [mode, setMode] = useState<Mode>("manual");

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <Button variant="primary" onClick={() => setOpen(true)}>
        Neuer Workflow
      </Button>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Neuer Workflow</DialogTitle>
        </DialogHeader>

        <div className="border-border mb-4 flex gap-1 border-b">
          <TabButton active={mode === "manual"} onClick={() => setMode("manual")}>
            Manuell erstellen
          </TabButton>
          <TabButton active={mode === "ai"} onClick={() => setMode("ai")}>
            <Sparkles className="size-3.5" />
            Mit KI erstellen
          </TabButton>
        </div>

        {mode === "manual" ? (
          <ManualTab formId={formId} />
        ) : (
          <AiTab formId={formId} onClose={() => setOpen(false)} />
        )}
      </DialogContent>
    </Dialog>
  );
}

function TabButton({
  active,
  onClick,
  children,
}: {
  active: boolean;
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "flex items-center gap-1.5 border-b-2 px-3 py-2 text-sm font-medium",
        active
          ? "border-primary text-primary-text"
          : "text-text-secondary hover:text-text-primary border-transparent",
      )}
    >
      {children}
    </button>
  );
}

function ManualTab({ formId }: { formId: string }) {
  const [, formAction, isPending] = useActionState(async (_: void, formData: FormData) => {
    await createWorkflowAction(formData);
  }, undefined);

  return (
    <form action={formAction} className="space-y-4">
      <input type="hidden" name="formId" value={formId} />
      <div className="space-y-1.5">
        <Label htmlFor="new-workflow-name">Name</Label>
        <Input
          id="new-workflow-name"
          name="name"
          placeholder="z. B. Lead-Benachrichtigung"
          required
        />
      </div>
      <DialogFooter>
        <Button type="submit" variant="primary" disabled={isPending}>
          {isPending ? "Wird erstellt…" : "Workflow erstellen"}
        </Button>
      </DialogFooter>
    </form>
  );
}

function AiTab({ formId, onClose }: { formId: string; onClose: () => void }) {
  const router = useRouter();
  const [description, setDescription] = useState("");
  const [isPending, setIsPending] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleGenerate() {
    setIsPending(true);
    setError(null);
    try {
      const response = await fetch("/api/ai/generate-workflow", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ formId, description: description.trim() }),
      });
      const body = await response.json();
      if (!response.ok) {
        setError(body.error?.message ?? "Workflow konnte nicht generiert werden.");
        setIsPending(false);
        return;
      }
      onClose();
      router.push(`/forms/${formId}/workflows/${body.workflowId}`);
    } catch {
      setError("Workflow konnte nicht generiert werden.");
      setIsPending(false);
    }
  }

  return (
    <div className="space-y-4">
      <div className="space-y-1.5">
        <Label htmlFor="ai-workflow-description">Beschreibe den gewünschten Workflow</Label>
        <Textarea
          id="ai-workflow-description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="z. B. Wenn das Budget unter 2.000 € liegt, sende eine Webhook-Benachrichtigung an Slack. Ansonsten sende eine Willkommens-E-Mail an den Ersteller."
          rows={5}
          minLength={10}
          maxLength={2000}
        />
      </div>
      {error ? (
        <p role="alert" className="text-error text-sm">
          {error}
        </p>
      ) : null}
      <DialogFooter>
        <Button
          type="button"
          variant="primary"
          onClick={handleGenerate}
          disabled={isPending || description.trim().length < 10}
        >
          {isPending ? "Wird generiert…" : "Workflow generieren"}
        </Button>
      </DialogFooter>
    </div>
  );
}
